INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (1, N'Can add log entry', 1, N'add_logentry');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (2, N'Can change log entry', 1, N'change_logentry');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (3, N'Can delete log entry', 1, N'delete_logentry');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (4, N'Can view log entry', 1, N'view_logentry');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (5, N'Can add permission', 2, N'add_permission');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (6, N'Can change permission', 2, N'change_permission');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (7, N'Can delete permission', 2, N'delete_permission');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (8, N'Can view permission', 2, N'view_permission');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (9, N'Can add group', 3, N'add_group');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (10, N'Can change group', 3, N'change_group');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (11, N'Can delete group', 3, N'delete_group');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (12, N'Can view group', 3, N'view_group');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (13, N'Can add user', 4, N'add_user');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (14, N'Can change user', 4, N'change_user');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (15, N'Can delete user', 4, N'delete_user');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (16, N'Can view user', 4, N'view_user');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (17, N'Can add content type', 5, N'add_contenttype');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (18, N'Can change content type', 5, N'change_contenttype');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (19, N'Can delete content type', 5, N'delete_contenttype');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (20, N'Can view content type', 5, N'view_contenttype');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (21, N'Can add session', 6, N'add_session');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (22, N'Can change session', 6, N'change_session');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (23, N'Can delete session', 6, N'delete_session');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (24, N'Can view session', 6, N'view_session');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (25, N'Can add customer', 7, N'add_customer');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (26, N'Can change customer', 7, N'change_customer');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (27, N'Can delete customer', 7, N'delete_customer');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (28, N'Can view customer', 7, N'view_customer');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (29, N'Can add department', 8, N'add_department');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (30, N'Can change department', 8, N'change_department');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (31, N'Can delete department', 8, N'delete_department');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (32, N'Can view department', 8, N'view_department');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (33, N'Can add employee', 9, N'add_employee');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (34, N'Can change employee', 9, N'change_employee');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (35, N'Can delete employee', 9, N'delete_employee');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (36, N'Can view employee', 9, N'view_employee');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (37, N'Can add appointment', 10, N'add_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (38, N'Can change appointment', 10, N'change_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (39, N'Can delete appointment', 10, N'delete_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (40, N'Can view appointment', 10, N'view_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (41, N'Can change own appointment', 10, N'change_own_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (42, N'Can change other appointment', 10, N'change_other_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (43, N'Can delete own appointment', 10, N'delete_own_appointment');
INSERT INTO master.dbo.auth_permission (id, name, content_type_id, codename) VALUES (44, N'Can delete other appointment', 10, N'delete_other_appointment');
